name: sweep-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _tflow_select
  - absl-py
  - asn1crypto
  - astor
  - astropy
  - atomicwrites
  - attrs
  - backcall
  - bazel
  - beautifulsoup4
  - blas
  - bleach
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - conda
  - conda-build
  - conda-package-handling
  - cryptography
  # - cudatoolkit
  # - cudnn
  # - cupti
  - cycler
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - filelock
  - fontconfig
  - freetype
  - future
  - gast
  - glib
  - glob2
  - gmp
  - google-pasta
  - grpcio
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5
  - icu
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyterthemes
  - keras
  - keras-applications
  - keras-base
  - keras-preprocessing
  - kiwisolver
  - libarchive
  - libedit
  - libffi
  # - libgcc-ng
  - libgfortran-ng
  - liblief
  - libpng
  - libprotobuf
  - libsodium
  # - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - libxslt
  - llvmlite
  - lxml
  - lz4-c
  - lzo
  - markdown
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mock
  - more-itertools
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numba
  - numpy
  - numpy-base
  - olefile
  - openjdk
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  # - patchelf
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkginfo
  - plotly
  - pluggy
  - prometheus_client
  - prompt_toolkit
  - protobuf
  - psutil
  - ptyprocess
  - py
  - py-lief
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - pytest
  - pytest-arraydiff
  - pytest-astropy
  - pytest-doctestplus
  - pytest-openfiles
  - pytest-remotedata
  - python
  - python-dateutil
  - python-libarchive-c
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - readline
  - requests
  - retrying
  - ruamel_yaml
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - soupsieve
  - sqlite
  - tensorboard
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  # - tensorflow-gpu
  - termcolor
  - terminado
  - testpath
  - tk
  - tornado
  - tqdm
  - traitlets
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - wrapt
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - argh
    - backports-tempfile
    - backports-weakref
    - bapsflib
    - click
    - comet-git-pure
    - comet-ml
    - configobj
    - docker-pycreds
    - everett
    - gitdb2
    - gitpython
    - gql
    - graphql-core
    - idna
    - jsonschema
    - lesscpy
    - netifaces
    - nvidia-ml-py3
    - pathtools
    - ply
    - promise
    - pyrsistent
    - rx
    - sentry-sdk
    - shortuuid
    - smmap2
    - subprocess32
    - urllib3
    - wandb
    - watchdog
    - websocket-client
    - wurlitzer

